---
title: "Homework 2"
format: gfm
---

```{r}
#| label: setup
#| include: false
knitr::opts_chunk$set(echo = TRUE)
```

### Overview

The goal of homework 2 is to manipulate and explore a dataset with the `dplyr` package, complemented by visualizations made with `ggplot2`.

Remember the [sampler concept](http://en.wikipedia.org/wiki/Sampler_(needlework)). Your homework should serve as your own personal cheatsheet in the future for ways to manipulate a dataset and produce companion figures. Give yourself the cheatsheet you deserve!

#### Gapminder data

Work with the `gapminder` package.

### Your mission, high-level

Pick at least three of the tasks below and attack each with a table and figure.

-   `dplyr` should be your main data manipulation tool
-   `ggplot2` should be your main visualization tool

Make observations about what your tables/figures show and about the process.

If you want to do something comparable but different, i.e. swap one quantitative variable for another, be my guest! If you are feeling inspired and curious, then we're doing this right. Go for it.

### Task menu

Get the maximum and minimum of GDP per capita for all continents.

Look at the spread of GDP per capita within the continents.

Compute a trimmed mean of life expectancy for different years. Or a weighted mean, weighting by population. Just try something other than the plain vanilla mean.

How is life expectancy changing over time on different continents?

Report the absolute and/or relative abundance of countries with low life expectancy over time by continent: Compute some measure of worldwide life expectancy – you decide – a mean or median or some other quantile or perhaps your current age. The determine how many countries on each continent have a life expectancy less than this benchmark, for each year.

Find countries with interesting stories. Open-ended and, therefore, hard. Promising but unsuccessful attempts are encouraged. This will generate interesting questions to follow up on in class.

Make up your own! Between the `dplyr` coverage in class and the list above, I think you get the idea.

### Companion graphs

For each table, make sure to include a relevant figure.

Your figure does not have to depict every last number from the data aggregation result. Use your judgment. It just needs to complement the table and add insights.

Notice which figures are easy/hard to make, which data formats make better inputs for plotting functions vs. for human-friendly tables.

### But I want to do more!

**Plot stretch goal:** Make your assignment pop with a nice color palette. Explore the palettes [viridis](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html), [ghibli](https://github.com/ewenme/ghibli), [wesanderson](https://github.com/karthik/wesanderson), or another of you choosing. Get them working in your plots.

**Table stretch goal:** Explore some really nice fancy table helper packages. For example, try working with the [gt](https://gt.rstudio.com/) package. For some table inspiration, take a look at the winners of Rstudio's recent [table competition](https://blog.rstudio.com/2020/12/23/winners-of-the-2020-rstudio-table-contest/).

### Report your process

You're encouraged to reflect on what was hard/easy, problems you solved, helpful tutorials you read, etc. Give credit to your sources, whether it's a blog post, a fellow student, an online tutorial, etc.

### Rubric

As always, refer to the [general rubric](general-rubric.md) for guidelines on how we'll be grading.

Check minus: Didn't tackle at least 3 tasks. Or didn't make companion graphs. Didn't interpret anything but left it all to the "reader". Or more than one technical problem that is relatively easy to fix. It's hard to find the report in your Rproject folder

Check: Hits all the elements. No obvious mistakes. Pleasant to read. No heroic detective work required. Solid.

Check plus: Exceeded the requirements in number of tasks. Or developed novel tasks that were indeed interesting and "worked". Impressive use of `dplyr` and/or `ggplot2`. Impeccable organization of your report. We learned something new from reviewing your work and are eager to incorporate it into our own work.
